apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: ns-meitavi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-sc-nitzanim
  volumeName: db-pv-meitavi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-data
  namespace: ns-meitavi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-sc-nitzanim
  volumeName: wp-pv-meitavi

