apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: ns-meitavi
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  
